[package]
name = "vados"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
build_html = "2.0.0"
serde = {version = "1.0.135", features = ["derive"]}
serde_json = "1.0.78"
